# version: 0.0
# os: linux

# files:
#   - source: /
#     destination: /var/www/html

# permissions:
#   - object: /
#     pattern: "**"
#     owner: root
#     group: root
#     mode: 755

# hooks:
#   AfterInstall:
#     - location: scripts/install_nginx.sh
#       timeout: 300
#       runas: root
#   ApplicationStart:
#     - location: scripts/start_nginx.sh
#       timeout: 300
#       runas: root
  
version: 0.0
os: linux

files:
  - source: /
    destination: /usr/share/nginx/html

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    mode: 755

hooks:
  BeforeInstall:
    - location: script/stop_nginx.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: script/start_nginx.sh
      timeout: 300
      runas: root
